embed_assets: datauri

javascripts:
  common:
    - public/javascripts/jquery-1.4.4.min.js
    - public/javascripts/farbtastic.js
    - public/javascripts/rails.js
    - public/javascripts/modernizr-1.6.min.js
    - public/javascripts/message.js
    - public/javascripts/site.js

stylesheets:
  common:
    - public/stylesheets/style.css
    - public/stylesheets/farbtastic.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/connecc.css
    - public/stylesheets/admin.css
    - public/stylesheets/about_us.css
    - public/stylesheets/message.css
