package_assets: on
embed_assets: datauri

javascripts:
  common:
    - public/javascripts/jquery-1.4.4.min.js
    - public/javascripts/modernizr-1.6.min.js
    - public/javascripts/site.js
    - public/javascripts/message.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/style.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/connecc.css
    - public/stylesheets/card.css
    - public/stylesheets/admin.css
    - public/stylesheets/about_us.css
    - public/stylesheets/message.css
